{ inputs, pkgs, ... }:

{
  imports = [ inputs.hyprdynamicmonitors.homeManagerModules.default ];

  home.hyprdynamicmonitors = {
    enable = true;

    # Configuration will be at ~/.config/hyprdynamicmonitors/config.toml
    config = ''
      [general]
      destination = "$HOME/.config/hypr/config.d/monitors.lua"
      debounce_time_ms = 1500
      # reload is needed for the dofile()d destination to be re-read
      post_apply_exec = "hyprctl reload; setsid monitor-post-apply >/dev/null 2>&1 &"

      [notifications]
      disabled = false
      timeout_ms = 5000

      [profiles.dual_monitors]
      config_file = "hyprconfigs/dual-monitors.go.tmpl"
      config_file_type = "template"

      [[profiles.dual_monitors.conditions.required_monitors]]
      name = "DP-1"
      monitor_tag = "monitor1"

      [[profiles.dual_monitors.conditions.required_monitors]]
      name = "DP-3"
      monitor_tag = "monitor2"

      [fallback_profile]
      config_file = "hyprconfigs/fallback.lua"
      config_file_type = "static"
    '';
    extraFiles = {
      "hyprdynamicmonitors/hyprconfigs/dual-monitors.go.tmpl" = pkgs.writeText "dual-monitors.go.tmpl" ''
        {{- $monitor1 := index .MonitorsByTag "monitor1" -}}
        {{- $monitor2 := index .MonitorsByTag "monitor2" -}}
        -- Auto-generated by HyprDynamicMonitors; do not edit.

        ----------------
        --  MONITORS  --
        ----------------
        hl.monitor({ output = "{{$monitor2.Name}}", mode = "2560x1440@164.80", position = "0x0", scale = 1 })
        hl.monitor({ output = "{{$monitor1.Name}}", mode = "2560x1440@164.80", position = "0x1440", scale = 1 })

        ------------------
        --  WORKSPACES  --
        ------------------
        local function ws(n, monitor, default)
          hl.workspace_rule({ workspace = tostring(n), monitor = monitor, default = default })
        end

        ws(1, "{{$monitor1.Name}}", true)
        ws(2, "{{$monitor1.Name}}")
        ws(3, "{{$monitor1.Name}}")
        ws(4, "{{$monitor1.Name}}")
        ws(5, "{{$monitor1.Name}}")
        ws(6, "{{$monitor2.Name}}", true)
        ws(7, "{{$monitor2.Name}}")
        ws(8, "{{$monitor2.Name}}")
        ws(9, "{{$monitor2.Name}}")
        ws(10, "{{$monitor2.Name}}")
        ws(11, "{{$monitor2.Name}}")
        ws(12, "{{$monitor2.Name}}")
      '';

      "hyprdynamicmonitors/hyprconfigs/fallback.lua" = pkgs.writeText "fallback.lua" ''
        -- Auto-generated by HyprDynamicMonitors (fallback); do not edit.

        ----------------
        --  MONITORS  --
        ----------------
        hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

        ------------------
        --  WORKSPACES  --
        ------------------
        local function ws(n, default)
          hl.workspace_rule({ workspace = tostring(n), default = default })
        end

        ws(1, true)
        ws(2)
        ws(3)
        ws(4)
        ws(5)
        ws(6)
        ws(7)
        ws(8)
        ws(9)
        ws(10)
        ws(11)
        ws(12)
      '';
    };
  };
}
