{ inputs, pkgs, ... }:

{
  imports = [ inputs.hyprdynamicmonitors.homeManagerModules.default ];

  home.hyprdynamicmonitors = {
    enable = true;

    # Configuration will be at ~/.config/hyprdynamicmonitors/config.toml
    config = ''
      [general]
      destination = "$HOME/.config/hypr/config.d/monitors.lua"
      debounce_time_ms = 1500
      # reload is needed for the dofile()d destination to be re-read
      post_apply_exec = "hyprctl reload; setsid monitor-post-apply >/dev/null 2>&1 &"

      [notifications]
      disabled = false
      timeout_ms = 5000

      # Profile 1: Laptop only
      [profiles.laptop_only]
      config_file = "hyprconfigs/laptop-only.go.tmpl"
      config_file_type = "template"

      [[profiles.laptop_only.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      # Profile 2: Docked - Lid Open
      [profiles.docked_lid_open]
      config_file = "hyprconfigs/docked-lid-open.go.tmpl"
      config_file_type = "template"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046C"
      monitor_tag = "external1"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046B"
      monitor_tag = "external2"

      # Profile 3: Docked - Lid Closed
      [profiles.docked_lid_closed]
      config_file = "hyprconfigs/docked-lid-closed.go.tmpl"
      config_file_type = "template"

      [profiles.docked_lid_closed.conditions]
      lid_state = "Closed"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046C"
      monitor_tag = "external1"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046B"
      monitor_tag = "external2"

      # Profile 4: Beamer
      [profiles.beamer]
      config_file = "hyprconfigs/beamer.go.tmpl"
      config_file_type = "template"

      [[profiles.beamer.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      [[profiles.beamer.conditions.required_monitors]]
      description = "Acer Technologies PD1520Us 0x00000001"
      monitor_tag = "beamer"
    '';

    extraFiles = {
      # Laptop only profile
      "hyprdynamicmonitors/hyprconfigs/laptop-only.go.tmpl" = pkgs.writeText "laptop-only.go.tmpl" ''
        {{- $laptop := index .MonitorsByTag "laptop" -}}
        -- Auto-generated by HyprDynamicMonitors; do not edit.

        ----------------
        --  MONITORS  --
        ----------------
        hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

        ------------------
        --  WORKSPACES  --
        ------------------
        local function ws(n, monitor, default)
          hl.workspace_rule({ workspace = tostring(n), monitor = monitor, default = default })
        end

        ws(1, "{{$laptop.Name}}", true)
        ws(2, "{{$laptop.Name}}")
        ws(3, "{{$laptop.Name}}")
        ws(4, "{{$laptop.Name}}")
        ws(5, "{{$laptop.Name}}")
        ws(6, "{{$laptop.Name}}")
        ws(7, "{{$laptop.Name}}")
        ws(8, "{{$laptop.Name}}")
        ws(9, "{{$laptop.Name}}")
        ws(10, "{{$laptop.Name}}")
        ws(11, "{{$laptop.Name}}")
        ws(12, "{{$laptop.Name}}")
      '';

      # Docked with lid open (triple monitor setup)
      "hyprdynamicmonitors/hyprconfigs/docked-lid-open.go.tmpl" =
        pkgs.writeText "docked-lid-open.go.tmpl" ''
          {{- $laptop := index .MonitorsByTag "laptop" -}}
          {{- $external1 := index .MonitorsByTag "external1" -}}
          {{- $external2 := index .MonitorsByTag "external2" -}}
          -- Auto-generated by HyprDynamicMonitors; do not edit.

          ----------------
          --  MONITORS  --
          ----------------
          hl.monitor({ output = "{{$laptop.Name}}", mode = "1920x1200@60", position = "2560x1680", scale = 1.5 })
          hl.monitor({ output = "{{$external1.Name}}", mode = "2560x1440@60", position = "0x1440", scale = 1 })
          hl.monitor({ output = "{{$external2.Name}}", mode = "2560x1440@60", position = "0x0", scale = 1 })

          ------------------
          --  WORKSPACES  --
          ------------------
          local function ws(n, monitor, default)
            hl.workspace_rule({ workspace = tostring(n), monitor = monitor, default = default })
          end

          ws(1, "{{$external1.Name}}", true)
          ws(2, "{{$external1.Name}}")
          ws(3, "{{$external1.Name}}")
          ws(4, "{{$external1.Name}}")
          ws(5, "{{$external1.Name}}")

          ws(6, "{{$external2.Name}}", true)
          ws(7, "{{$external2.Name}}")
          ws(8, "{{$external2.Name}}")
          ws(9, "{{$external2.Name}}")

          ws(10, "{{$laptop.Name}}", true)
          ws(11, "{{$laptop.Name}}")
          ws(12, "{{$laptop.Name}}")
        '';

      # Docked with lid closed (dual external monitors only)
      "hyprdynamicmonitors/hyprconfigs/docked-lid-closed.go.tmpl" =
        pkgs.writeText "docked-lid-closed.go.tmpl" ''
          {{- $laptop := index .MonitorsByTag "laptop" -}}
          {{- $external1 := index .MonitorsByTag "external1" -}}
          {{- $external2 := index .MonitorsByTag "external2" -}}
          -- Auto-generated by HyprDynamicMonitors; do not edit.

          ----------------
          --  MONITORS  --
          ----------------
          hl.monitor({ output = "{{$laptop.Name}}", disabled = true })
          hl.monitor({ output = "{{$external1.Name}}", mode = "2560x1440@60", position = "0x1440", scale = 1 })
          hl.monitor({ output = "{{$external2.Name}}", mode = "2560x1440@60", position = "0x0", scale = 1 })

          ------------------
          --  WORKSPACES  --
          ------------------
          local function ws(n, monitor, default)
            hl.workspace_rule({ workspace = tostring(n), monitor = monitor, default = default })
          end

          ws(1, "{{$external1.Name}}", true)
          ws(2, "{{$external1.Name}}")
          ws(3, "{{$external1.Name}}")
          ws(4, "{{$external1.Name}}")
          ws(5, "{{$external1.Name}}")

          ws(6, "{{$external2.Name}}", true)
          ws(7, "{{$external2.Name}}")
          ws(8, "{{$external2.Name}}")
          ws(9, "{{$external2.Name}}")
          ws(10, "{{$external2.Name}}")
          ws(11, "{{$external2.Name}}")
          ws(12, "{{$external2.Name}}")
        '';

      # Beamer profile
      "hyprdynamicmonitors/hyprconfigs/beamer.go.tmpl" = pkgs.writeText "beamer.go.tmpl" ''
        {{- $laptop := index .MonitorsByTag "laptop" -}}
        {{- $beamer := index .MonitorsByTag "beamer" -}}
        -- Auto-generated by HyprDynamicMonitors; do not edit.

        ----------------
        --  MONITORS  --
        ----------------
        hl.monitor({ output = "{{$laptop.Name}}", mode = "1920x1200@60", position = "0x0", scale = 1 })
        hl.monitor({ output = "{{$beamer.Name}}", mode = "1920x1080@60", position = "1920x0", scale = 1 })

        ------------------
        --  WORKSPACES  --
        ------------------
        local function ws(n, monitor, default)
          hl.workspace_rule({ workspace = tostring(n), monitor = monitor, default = default })
        end

        ws(1, "{{$laptop.Name}}", true)
        ws(2, "{{$laptop.Name}}")
        ws(3, "{{$laptop.Name}}")
        ws(4, "{{$laptop.Name}}")
        ws(5, "{{$laptop.Name}}")
        ws(6, "{{$laptop.Name}}")
        ws(7, "{{$laptop.Name}}")
        ws(8, "{{$laptop.Name}}")
        ws(9, "{{$laptop.Name}}")

        ws(10, "{{$beamer.Name}}", true)
        ws(11, "{{$beamer.Name}}")
        ws(12, "{{$beamer.Name}}")
      '';
    };

    extraFlags = [ "--enable-lid-events" ];
  };
}
