{ inputs, pkgs, ... }:

{
  imports = [ inputs.hyprdynamicmonitors.homeManagerModules.default ];

  home.hyprdynamicmonitors = {
    enable = true;

    # Configuration will be at ~/.config/hyprdynamicmonitors/config.toml
    config = ''
      [general]
      destination = "$HOME/.config/hypr/config.d/99_autogenerated-monitors.conf"
      debounce_time_ms = 1500
      post_apply_exec = "setsid restart-ags >/dev/null 2>&1 &"

      [notifications]
      disabled = false
      timeout_ms = 5000

      # Profile 1: Laptop only
      [profiles.laptop_only]
      config_file = "hyprconfigs/laptop-only.go.tmpl"
      config_file_type = "template"

      [[profiles.laptop_only.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      # Profile 2: Docked - Lid Open
      [profiles.docked_lid_open]
      config_file = "hyprconfigs/docked-lid-open.go.tmpl"
      config_file_type = "template"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046C"
      monitor_tag = "external1"

      [[profiles.docked_lid_open.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046B"
      monitor_tag = "external2"

      # Profile 2: Docked - Lid Closed
      [profiles.docked_lid_closed]
      config_file = "hyprconfigs/docked-lid-closed.go.tmpl"
      config_file_type = "template"

      [profiles.docked_lid_closed.conditions]
      lid_state = "Closed"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "laptop"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046C"
      monitor_tag = "external1"

      [[profiles.docked_lid_closed.conditions.required_monitors]]
      description = "GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x0000046B"
      monitor_tag = "external2"
    '';

    # Install monitor profile templates
    extraFiles = {
      # Laptop only profile
      "hyprdynamicmonitors/hyprconfigs/laptop-only.go.tmpl" =
        pkgs.writeText "laptop-only.go.tmpl" ''
          {{- $laptop := index .MonitorsByTag "laptop" -}}

          ####################
          ###   MONITORS   ###
          ####################

          monitor = , preferred, auto, 1

          ####################
          ###  WORKSPACES  ###
          ####################

          workspace=1,monitor:{{$laptop.Name}},default:true
          workspace=2,monitor:{{$laptop.Name}}
          workspace=3,monitor:{{$laptop.Name}}
          workspace=4,monitor:{{$laptop.Name}}
          workspace=5,monitor:{{$laptop.Name}}
          workspace=6,monitor:{{$laptop.Name}}
          workspace=7,monitor:{{$laptop.Name}}
          workspace=8,monitor:{{$laptop.Name}}
          workspace=9,monitor:{{$laptop.Name}}
          workspace=10,monitor:{{$laptop.Name}}
        '';

      # Docked with lid open (triple monitor setup)
      "hyprdynamicmonitors/hyprconfigs/docked-lid-open.go.tmpl" =
        pkgs.writeText "docked-lid-open.go.tmpl" ''
          {{- $laptop := index .MonitorsByTag "laptop" -}}
          {{- $external1 := index .MonitorsByTag "external1" -}}
          {{- $external2 := index .MonitorsByTag "external2" -}}

          ####################
          ###   MONITORS   ###
          ####################

          monitor={{$laptop.Name}},1920x1200@60,2560x1680,1.5
          monitor={{$external1.Name}},2560x1440@60,0x1440,1
          monitor={{$external2.Name}},2560x1440@60,0x0,1

          ####################
          ###  WORKSPACES  ###
          ####################

          workspace=1,monitor:{{$external1.Name}},default:true
          workspace=2,monitor:{{$external1.Name}}
          workspace=3,monitor:{{$external1.Name}}
          workspace=4,monitor:{{$external1.Name}}
          workspace=5,monitor:{{$external1.Name}}

          workspace=6,monitor:{{$external2.Name}},default:true
          workspace=7,monitor:{{$external2.Name}}
          workspace=8,monitor:{{$external2.Name}}
          workspace=9,monitor:{{$external2.Name}}

          workspace=10,monitor:{{$laptop.Name}},default:true
        '';

      # Docked with lid closed (dual external monitors only)
      "hyprdynamicmonitors/hyprconfigs/docked-lid-closed.go.tmpl" =
        pkgs.writeText "docked-lid-closed.go.tmpl" ''
          {{- $laptop := index .MonitorsByTag "laptop" -}}
          {{- $external1 := index .MonitorsByTag "external1" -}}
          {{- $external2 := index .MonitorsByTag "external2" -}}

          ####################
          ###   MONITORS   ###
          ####################

          monitor={{$laptop.Name}},disable
          monitor={{$external1.Name}},2560x1440@60,0x1440,1
          monitor={{$external2.Name}},2560x1440@60,0x0,1

          ####################
          ###  WORKSPACES  ###
          ####################

          workspace=1,monitor:{{$external1.Name}},default:true
          workspace=2,monitor:{{$external1.Name}}
          workspace=3,monitor:{{$external1.Name}}
          workspace=4,monitor:{{$external1.Name}}
          workspace=5,monitor:{{$external1.Name}}

          workspace=6,monitor:{{$external2.Name}},default:true
          workspace=7,monitor:{{$external2.Name}}
          workspace=8,monitor:{{$external2.Name}}
          workspace=9,monitor:{{$external2.Name}}
          workspace=10,monitor:{{$external2.Name}}
        '';
    };

    extraFlags = [ "--enable-lid-events" ];

    systemdTarget = "graphical-session.target";
  };
}
