{ pkgs, config, lib, inputs, ... }:

# Note: HYPRCURSOR_THEME and HYPRCURSOR_SIZE are defined in /home-manager/gtk/default.nix
#
# https://nixos.wiki/wiki/Hyprland#Using_Home_Manager

{
  wayland.windowManager.hyprland = {
    enable = true;
    package =
      inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    xwayland.enable = true;

    extraConfig = ''
      $path = $HOME/.config/hypr

      $mainMod = SUPER

      source=$path/config.d/99_autogenerated-monitors.conf
      source=$path/windows.conf
      source=$path/startup_apps.conf
      source=$path/keybinds.conf
      source=$path/behavior.conf
      source=$path/input.conf
      source=$path/app_keybinds.conf
    '';

    # disabled because it will start with the login manager
    # also it causes conflicts with our config
    systemd.enable = false;
  };

  # https://wiki.hyprland.org/Hypr-Ecosystem/
  home.packages = with pkgs; [ wl-clipboard hyprcursor wtype ];

  # Create the config.d directory for HyprDynamicMonitors
  home.file.".config/hypr/config.d/.keep".text = "";

  home.file = {
    ".config/hypr/keybinds.conf".source = ./keybinds.conf;
    ".config/hypr/behavior.conf".source = ./behavior.conf;
    ".config/hypr/windows.conf".source = ./windows.conf;
    ".config/hypr/input.conf".source = ./input.conf;
    ".config/hypr/app_keybinds.conf".source = ./app_keybinds.conf;

    ".config/hypr/startup_apps.conf".source = ./laptop/startup_apps.conf;
  };
}
