##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Prevent windows from fullscreening themselves
# windowrule = suppress_event fullscreen maximize, match:class .*

windowrule {
    # Ignore maximize requests from all apps. 
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
  name = pip
  match:title = ^(Picture-in-Picture)$

  pin = on
  float = on
  keep_aspect_ratio = on
}

windowrule {
  name = steam-contacts
  match:title = ^(Liste de contacts)$

  float = on
  size = 332 75%
}

windowrule {
  name = gamescope
  match:class = ^(gamescope)$

  no_blur = on
}

windowrule {
  name = power-menu
  match:title = ^(rofi - Power Menu|rofi - Shutdown delay:)$

  float = on
  center = on
  dim_around = on
}

windowrule {
  name = thunar-rename
  match:class = ^(thunar)$
  match:title = Rename .*

  float = on
  dim_around = on
}

windowrule {
  # Prevents call window from following across workspaces
  name = kchat-call-popup
  match:class = ^(kChat)$
  match:title = ^(kChat)$

  float = on
  keep_aspect_ratio = on
  pin = on
}
